### ISSUE TITLE
Need features from cocos 3.15

### ISSUE THREAD

**Issue by crookedbard** [xpams/cocos2d-x-for-tvOS#1]
Would it be possible to merge cocos2d-x changes from 3.15 version?

**Comment by xpams** [comment]
Hello! As soon as I have free time - I can update the repository.

**Comment by crookedbard** [comment]
Excellent!! Thanks for fast response! I will be looking forward for the update!
I was missing some Sprite3d features like setMaterial and also some DrawNode features.
Will be exciting to test out my project on apple tv finally :)

**Comment by xpams** [comment]
@crookedbard, I haven't apple tv. please check test branch 3.15:)

**Comment by crookedbard** [comment]
when I try to run the example on apple tv xcode throws:
ld: in /Users/daini_000/Library/Developer/Xcode/DerivedData/tvapp-gctpqnbppkxjhhecbxxmrmsnjtir/Build/Products/Debug-appletvos/libcocos2d tvOS.a(ftbase.ios8_arm64.o), building for tvOS, but linking in object file built for iOS, for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Also there is no such macro predefined: CC_PLATFORM_TVOS
So it doesn't allow to use such commands:

[eaglView setMultipleTouchEnabled:NO];
_viewController.wantsFullScreenLayout = YES;
[[UIApplication sharedApplication] setStatusBarHidden:true];

**Comment by crookedbard** [comment]
also with target tvapp-mobile xcode throws:

Undefined symbols for architecture armv7:
  "_CTFramesetterCreateWithAttributedString", referenced from:
      _calculateShrinkedSizeForString(NSAttributedString**, objc_object*, CGSize, bool, int&) in libcocos2d iOS.a(CCDevice-ios.o)
  "_CTFramesetterSuggestFrameSizeWithConstraints", referenced from:
      _calculateShrinkedSizeForString(NSAttributedString**, objc_object*, CGSize, bool, int&) in libcocos2d iOS.a(CCDevice-ios.o)
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by xpams** [comment]
I don't know what your problem is:( I did compile the project without errors.

Please check the following things in your project:
1.
![screen shot 2017-09-01 at 1 14 22 pm](https://user-images.githubusercontent.com/2963789/29966023-b5644bf0-8f18-11e7-9ab2-7a194ad81354.png)
2.
![screen shot 2017-09-01 at 1 13 50 pm](https://user-images.githubusercontent.com/2963789/29966029-bb4b8308-8f18-11e7-8a4f-4748598c4f18.png)


If it does not help, try downloading the repository again:
  1.  git clone https://github.com/xpams/cocos2d-x-for-tvOS.git
  2.  cd cocos2d-x-for-tvOS/
  3.  git checkout 3.15

**Comment by xpams** [comment]
@crookedbard sorry, I forgot to make push of the final version.:((( Check please again branch 3.15.

**Comment by crookedbard** [comment]
It works! Awesome! [https://i.imgur.com/4Z1YlZb.jpg](https://i.imgur.com/4Z1YlZb.jpg)
Thanks for making this possible :)

**Comment by crookedbard** [comment]
but I just noticed that libcocos2d Mac doesn't build.

CCGLViewImpl-desktop.cpp
Line 600: glfwSetWindowMonitor - undeclared identifier
Line 613: GLFW_DONT_CARE - undeclared identifier

**Comment by crookedbard** [comment]
Just noticed that libcocos2d Mac doesn't build...
CCGLViewImpl-desktop.cpp
Line 600: glfwSetWindowMonitor - use of undeclared identifier
Line 613: GLFW_DONT_CARE  - use of undeclared identifier
