### ISSUE TITLE
Need update for cocos2d-x 4.0 Metal version

### ISSUE THREAD

**Issue by crookedbard** [xpams/cocos2d-x-for-tvOS#6]

**Comment by xpams** [comment]
we are already working with a new version of cocos2d-x. as soon as we connect apple tv, I will update the repository

**Comment by crookedbard** [comment]
Awesome! I will be looking forward to it. Thanks for fast response!

**Comment by xpams** [comment]
Today I received the first successful build!

I will try to make update in the near future.
